project = "premium-guide-403909"
region = "europe-central2"
zone = "europe-central2-a"
subnet_cidr_block = "10.10.0.0/24"
vpc_network_name = "atlantis-demo-network"
vpc_subnetwork_name = "atlantis-demo-subnetwork!"
